name: Deploy to Google App Engine

on:
    push:
        branches:
            - main # Trigger workflow for prod

jobs:
    deploy:
        runs-on: ubuntu-latest

        env: 
          PROJECT_ID: kai-ai-f63c8
          ENV_TYPE: sandbox
    
        steps:
        - name: Checkout
          uses: actions/checkout@v2
        
        - name: GCP Auth for Production
          if: github.ref == 'refs/heads/main'
          uses: 'google-github-actions/auth@v1'
          with:
            credentials_json: ${{ secrets.PRODUCTION_CREDENTIALS_JSON }}
        
        - name: 'Set up Cloud SDK'
          uses: 'google-github-actions/setup-gcloud@v1'
          with:
            version: '>= 363.0.0'
        
        - name: Deploy To App Engine (Production)
          if: github.ref == 'refs/heads/main'
          uses: 'google-github-actions/deploy-appengine@v0.2.0'
          with:
            deliverables: app/app.yaml
            version: v1