name: Deploy to Google App Engine

on:
    push:
        branches:
            - main # Trigger workflow for prod

jobs:
    deploy:
        runs-on: ubuntu-latest
    
        steps:
        - name: Checkout
          uses: actions/checkout@v2
        
        - name: GCP Auth for Production
          if: github.ref == 'refs/heads/main'
          uses: 'google-github-actions/auth@v1'
          with:
            credentials: ${{ secrets.PRODUCTION_CREDENTIALS }}
        
        - name: 'Set up Cloud SDK'
          uses: 'google-github-actions/setup-gcloud@v1'
          with:
            version: '>= 363.0.0'
        
        - name: Set Google Application Credentials
          run: echo 'GOOGLE_APPLICATION_CREDENTIALS=${{ secrets.PRODUCTION_CREDENTIALS }}' >> $GITHUB_ENV
        
        - name: Deploy To App Engine (Production)
          if: github.ref == 'refs/heads/main'
          uses: 'google-github-actions/deploy-appengine@v0.2.0'
          with:
            deliverables: app.yaml
            version: v1
            credentials: '${{ secrets.PRODUCTION_CREDENTIALS }}'
